spring.application.name=playerservice

spring.datasource.url=${POST.URL.PLAYER_DB}
spring.datasource.username=${POST.USERNAME}
spring.datasource.password=${POST.PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop

server.port=8082