spring.application.name=authservice

spring.datasource.url=${POST.URL.USER_DB}
spring.datasource.username=${POST.USERNAME}
spring.datasource.password=${POST.PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret.key=${SECRET_KEY}
server.port=8081
